Repository oasis-tcs/sarif-spec, pull requests merged in 2025-03, with the labels that each got.

#674 Meeting minutes 2025-02-06
  meeting_minutes/250206_SARIF_TC_96.md
Labels: process

#675 Fix typo in XML example of logical locations (#669)
  sarif-2.2/prose/edit/src/file-format-33-logicallocation-object.md
Labels: resolved-fixed

#672 Editor Proposal for 574 adding a justification enumeration
  sarif-2.2/prose/edit/src/file-format-35-suppression-object.md
Labels: resolved-fixed, ready, to-be-discussed, proposal
