Repository oasis-tcs/sarif-spec, pull requests merged in 2025-08, with the labels that each got.

#713 Meeting minutes 2025-07-10
  meeting_minutes/250710_SARIF_TC_101.md
Labels: process

#714 Editor Revision 2025-07-10
  sarif-2.2/prose/edit/bin/toccata.py
  sarif-2.2/prose/edit/etc/liitos/bookmatter.tex.in
  sarif-2.2/prose/edit/src/changelog.md
  sarif-2.2/prose/edit/src/file-format-27-result-object.md
  sarif-2.2/prose/edit/src/frontmatter.md
  sarif-2.2/prose/edit/src/introduction-02-terminology-glossary.md
  sarif-2.2/prose/share/sarif-v2.2-draft.html
  sarif-2.2/prose/share/sarif-v2.2-draft.md
  sarif-2.2/prose/share/sarif-v2.2-draft.pdf
Labels: 2.2.0, to-be-discussed

#727 Fixed example 1 in 3.13.5 inline external properties
  sarif-2.2/example/example-3-13-5-01.json
  sarif-2.2/example/example-3-13-5-01.md
  sarif-2.2/example/example-3-3-15-01.md
  sarif-2.2/prose/edit/src/file-format-13-sariflog-object.md
  sarif-2.2/prose/edit/src/json-examples/file-format-13-sariflog-object_inlineexternalproperties-property_example-1.json
Labels: bug, 2.2, editorial, to-be-discussed

#728 Updated version value of example 1 extracted from section 3.3.4
  sarif-2.2/example/example-3-3-4-01.json
Labels: 2.2, editorial, to-be-discussed

#685 Update Future.md
  Future.md
Labels: to-be-discussed, proposal

#726 Meeting minutes 2025-08-07
  meeting_minutes/250807_SARIF_TC_102.md
Labels: process
